import { PrismaClient } from "@prisma/client";
import { PrismaClient as SqlitePrismaClient } from "../../prisma/generated/sqlite";
import { env } from "@/lib/config/env";
import { applyJsonCodec } from "@/lib/db-codec";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

/**
 * SQLite mode is enabled when DATABASE_URL points at a local file or when
 * AETHERIS_DB_MODE=sqlite is set explicitly. The SQLite Prisma client is
 * generated by `prisma generate --schema prisma/sqlite/schema.prisma` and
 * stores Json fields as JSON strings handled by the db-codec middleware.
 */
function isSqliteMode(): boolean {
  return env.DATABASE_URL.startsWith("file:") || process.env.AETHERIS_DB_MODE === "sqlite";
}

function createClient(): PrismaClient {
  if (isSqliteMode()) {
    const client = new SqlitePrismaClient() as unknown as PrismaClient;
    applyJsonCodec(client);
    return client;
  }
  return new PrismaClient({
    datasources: { db: { url: env.DATABASE_URL } },
    log: env.NODE_ENV === "development" ? ["warn", "error"] : ["error"]
  });
}

export const prisma = globalForPrisma.prisma ?? createClient();

if (env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
